// Pure helpers for the London Tube widget. Classic script (no export),
// exposes globalThis.Tube for both index.html and tube.test.mjs.
// TfL line/station names, colors, and Naptan stop IDs are published facts
// (tfl.gov.uk brand guidelines + open StopPoint data), not the third-party
// marketplace package this widget was rebuilt to avoid.
(function () {
  // name -> TfL Naptan stop ID, so the station picker resolves directly
  // without a runtime search-API round trip.
  const STATIONS = [
    { name: 'Abbey Wood', id: 'HUBABW' },
    { name: 'Acton Main Line', id: '910GACTONML' },
    { name: 'Acton Town', id: '940GZZLUACT' },
    { name: 'Aldgate', id: '940GZZLUALD' },
    { name: 'Aldgate East', id: '940GZZLUADE' },
    { name: 'Alperton', id: '940GZZLUALP' },
    { name: 'Amersham', id: '940GZZLUAMS' },
    { name: 'Angel', id: '940GZZLUAGL' },
    { name: 'Archway', id: '940GZZLUACY' },
    { name: 'Arnos Grove', id: '940GZZLUASG' },
    { name: 'Arsenal', id: '940GZZLUASL' },
    { name: 'Baker Street', id: '940GZZLUBST' },
    { name: 'Balham', id: '940GZZLUBLM' },
    { name: 'Bank', id: '940GZZDLBNK' },
    { name: 'Barbican', id: '940GZZLUBBN' },
    { name: 'Barking', id: '940GZZLUBKG' },
    { name: 'Barkingside', id: '940GZZLUBKE' },
    { name: 'Barons Court', id: '940GZZLUBSC' },
    { name: 'Battersea Power Station', id: '940GZZBPSUST' },
    { name: 'Bayswater', id: '940GZZLUBWT' },
    { name: 'Becontree', id: '940GZZLUBEC' },
    { name: 'Belsize Park', id: '940GZZLUBZP' },
    { name: 'Bermondsey', id: '940GZZLUBMY' },
    { name: 'Bethnal Green', id: '940GZZLUBLG' },
    { name: 'Blackfriars', id: '940GZZLUBKF' },
    { name: 'Blackhorse Road', id: '940GZZLUBLR' },
    { name: 'Bond Street', id: '940GZZLUBND' },
    { name: 'Borough', id: '940GZZLUBOR' },
    { name: 'Boston Manor', id: '940GZZLUBOS' },
    { name: 'Bounds Green', id: '940GZZLUBDS' },
    { name: 'Bow Road', id: '940GZZLUBWR' },
    { name: 'Brent Cross', id: '940GZZLUBTX' },
    { name: 'Brentwood', id: '910GBRTWOOD' },
    { name: 'Brixton', id: '940GZZLUBXN' },
    { name: 'Bromley-By-Bow', id: '940GZZLUBBB' },
    { name: 'Buckhurst Hill', id: '940GZZLUBKH' },
    { name: 'Burnham', id: '910GBNHAM' },
    { name: 'Burnt Oak', id: '940GZZLUBTK' },
    { name: 'Caledonian Road', id: '940GZZLUCAR' },
    { name: 'Camden Town', id: '940GZZLUCTN' },
    { name: 'Canada Water', id: '940GZZLUCWR' },
    { name: 'Canary Wharf', id: '940GZZDLCAN' },
    { name: 'Canning Town', id: '940GZZDLCGT' },
    { name: 'Cannon Street', id: '940GZZLUCST' },
    { name: 'Canons Park', id: '940GZZLUCPK' },
    { name: 'Chadwell Heath', id: '910GCHDWLHT' },
    { name: 'Chalfont & Latimer', id: '940GZZLUCAL' },
    { name: 'Chalk Farm', id: '940GZZLUCFM' },
    { name: 'Chancery Lane', id: '940GZZLUCHL' },
    { name: 'Charing Cross', id: '940GZZLUCHX' },
    { name: 'Chesham', id: '940GZZLUCSM' },
    { name: 'Chigwell', id: '940GZZLUCWL' },
    { name: 'Chiswick Park', id: '940GZZLUCWP' },
    { name: 'Chorleywood', id: '940GZZLUCYD' },
    { name: 'Clapham Common', id: '940GZZLUCPC' },
    { name: 'Clapham North', id: '940GZZLUCPN' },
    { name: 'Clapham South', id: '940GZZLUCPS' },
    { name: 'Cockfosters', id: '940GZZLUCKS' },
    { name: 'Colindale', id: '940GZZLUCND' },
    { name: 'Colliers Wood', id: '940GZZLUCSD' },
    { name: 'Covent Garden', id: '940GZZLUCGN' },
    { name: 'Croxley', id: '940GZZLUCXY' },
    { name: 'Custom House', id: 'HUBCUS' },
    { name: 'Custom House for ExCeL', id: '940GZZDLCUS' },
    { name: 'Dagenham East', id: '940GZZLUDGE' },
    { name: 'Dagenham Heathway', id: '940GZZLUDGY' },
    { name: 'Debden', id: '940GZZLUDBN' },
    { name: 'Dollis Hill', id: '940GZZLUDOH' },
    { name: 'Ealing Broadway', id: '940GZZLUEBY' },
    { name: 'Ealing Common', id: '940GZZLUECM' },
    { name: 'Earls Court', id: '940GZZLUECT' },
    { name: 'East Acton', id: '940GZZLUEAN' },
    { name: 'East Finchley', id: '940GZZLUEFY' },
    { name: 'East Ham', id: '940GZZLUEHM' },
    { name: 'East Putney', id: '940GZZLUEPY' },
    { name: 'Eastcote', id: '940GZZLUEAE' },
    { name: 'Edgware', id: '940GZZLUEGW' },
    { name: 'Edgware Road (Bakerloo)', id: '940GZZLUERB' },
    { name: 'Edgware Road (Circle Line)', id: '940GZZLUERC' },
    { name: 'Elephant & Castle', id: '940GZZLUEAC' },
    { name: 'Elm Park', id: '940GZZLUEPK' },
    { name: 'Embankment', id: '940GZZLUEMB' },
    { name: 'Epping', id: '940GZZLUEPG' },
    { name: 'Euston', id: '940GZZLUEUS' },
    { name: 'Euston Square', id: '940GZZLUESQ' },
    { name: 'Fairlop', id: '940GZZLUFLP' },
    { name: 'Farringdon', id: '940GZZLUFCN' },
    { name: 'Finchley Central', id: '940GZZLUFYC' },
    { name: 'Finchley Road', id: '940GZZLUFYR' },
    { name: 'Finsbury Park', id: '940GZZLUFPK' },
    { name: 'Forest Gate', id: '910GFRSTGT' },
    { name: 'Fulham Broadway', id: '940GZZLUFBY' },
    { name: 'Gants Hill', id: '940GZZLUGTH' },
    { name: 'Gidea Park', id: '910GGIDEAPK' },
    { name: 'Gloucester Road', id: '940GZZLUGTR' },
    { name: 'Golders Green', id: '940GZZLUGGN' },
    { name: 'Goldhawk Road', id: '940GZZLUGHK' },
    { name: 'Goodge Street', id: '940GZZLUGDG' },
    { name: 'Goodmayes', id: '910GGODMAYS' },
    { name: 'Grange Hill', id: '940GZZLUGGH' },
    { name: 'Great Portland Street', id: '940GZZLUGPS' },
    { name: 'Green Park', id: '940GZZLUGPK' },
    { name: 'Greenford', id: '940GZZLUGFD' },
    { name: 'Gunnersbury', id: '940GZZLUGBY' },
    { name: 'Hainault', id: '940GZZLUHLT' },
    { name: 'Hammersmith', id: '940GZZLUHSD' },
    { name: 'Hampstead', id: '940GZZLUHTD' },
    { name: 'Hanger Lane', id: '940GZZLUHGR' },
    { name: 'Hanwell', id: '910GHANWELL' },
    { name: 'Harlesden', id: '940GZZLUHSN' },
    { name: 'Harold Wood', id: '910GHRLDWOD' },
    { name: 'Harrow & Wealdstone', id: '940GZZLUHAW' },
    { name: 'Harrow-on-the-Hill', id: '940GZZLUHOH' },
    { name: 'Hatton Cross', id: '940GZZLUHNX' },
    { name: 'Hayes & Harlington', id: '910GHAYESAH' },
    { name: 'Heathrow Terminal 4', id: '940GZZLUHR4' },
    { name: 'Heathrow Terminal 5', id: '940GZZLUHR5' },
    { name: 'Heathrow Terminals 2 & 3', id: '940GZZLUHRC' },
    { name: 'Hendon Central', id: '940GZZLUHCL' },
    { name: 'High Barnet', id: '940GZZLUHBT' },
    { name: 'High Street Kensington', id: '940GZZLUHSK' },
    { name: 'Highbury & Islington', id: '940GZZLUHAI' },
    { name: 'Highgate', id: '940GZZLUHGT' },
    { name: 'Hillingdon', id: '940GZZLUHGD' },
    { name: 'Holborn', id: '940GZZLUHBN' },
    { name: 'Holland Park', id: '940GZZLUHPK' },
    { name: 'Holloway Road', id: '940GZZLUHWY' },
    { name: 'Hornchurch', id: '940GZZLUHCH' },
    { name: 'Hounslow Central', id: '940GZZLUHWC' },
    { name: 'Hounslow East', id: '940GZZLUHWE' },
    { name: 'Hounslow West', id: '940GZZLUHWT' },
    { name: 'Hyde Park Corner', id: '940GZZLUHPC' },
    { name: 'Ickenham', id: '940GZZLUICK' },
    { name: 'Ilford', id: '910GILFORD' },
    { name: 'Iver', id: '910GIVER' },
    { name: 'Kennington', id: '940GZZLUKNG' },
    { name: 'Kensal Green', id: '940GZZLUKSL' },
    { name: 'Kensington (Olympia)', id: '940GZZLUKOY' },
    { name: 'Kentish Town', id: '940GZZLUKSH' },
    { name: 'Kenton', id: '940GZZLUKEN' },
    { name: 'Kew Gardens', id: '940GZZLUKWG' },
    { name: 'Kilburn', id: '940GZZLUKBN' },
    { name: 'Kilburn Park', id: '940GZZLUKPK' },
    { name: 'Kings Cross St. Pancras', id: '940GZZLUKSX' },
    { name: 'Kingsbury', id: '940GZZLUKBY' },
    { name: 'Knightsbridge', id: '940GZZLUKNB' },
    { name: 'Ladbroke Grove', id: '940GZZLULAD' },
    { name: 'Lambeth North', id: '940GZZLULBN' },
    { name: 'Lancaster Gate', id: '940GZZLULGT' },
    { name: 'Langley', id: '910GLANGLEY' },
    { name: 'Latimer Road', id: '940GZZLULRD' },
    { name: 'Leicester Square', id: '940GZZLULSQ' },
    { name: 'Leyton', id: '940GZZLULYN' },
    { name: 'Leytonstone', id: '940GZZLULYS' },
    { name: 'Liverpool Street', id: '940GZZLULVT' },
    { name: 'London Bridge', id: '940GZZLULNB' },
    { name: 'Loughton', id: '940GZZLULGN' },
    { name: 'Maida Vale', id: '940GZZLUMVL' },
    { name: 'Maidenhead', id: '910GMDNHEAD' },
    { name: 'Manor House', id: '940GZZLUMRH' },
    { name: 'Manor Park', id: '910GMANRPK' },
    { name: 'Mansion House', id: '940GZZLUMSH' },
    { name: 'Marble Arch', id: '940GZZLUMBA' },
    { name: 'Maryland', id: '910GMRYLAND' },
    { name: 'Marylebone', id: '940GZZLUMYB' },
    { name: 'Mile End', id: '940GZZLUMED' },
    { name: 'Mill Hill East', id: '940GZZLUMHL' },
    { name: 'Monument', id: '940GZZLUMMT' },
    { name: 'Moor Park', id: '940GZZLUMPK' },
    { name: 'Moorgate', id: '940GZZLUMGT' },
    { name: 'Morden', id: '940GZZLUMDN' },
    { name: 'Mornington Crescent', id: '940GZZLUMTC' },
    { name: 'Neasden', id: '940GZZLUNDN' },
    { name: 'Newbury Park', id: '940GZZLUNBP' },
    { name: 'Nine Elms', id: '940GZZNEUGST' },
    { name: 'North Acton', id: '940GZZLUNAN' },
    { name: 'North Ealing', id: '940GZZLUNEN' },
    { name: 'North Greenwich', id: '940GZZLUNGW' },
    { name: 'North Harrow', id: '940GZZLUNHA' },
    { name: 'North Wembley', id: '940GZZLUNWY' },
    { name: 'Northfields', id: '940GZZLUNFD' },
    { name: 'Northolt', id: '940GZZLUNHT' },
    { name: 'Northwick Park', id: '940GZZLUNKP' },
    { name: 'Northwood', id: '940GZZLUNOW' },
    { name: 'Northwood Hills', id: '940GZZLUNWH' },
    { name: 'Notting Hill Gate', id: '940GZZLUNHG' },
    { name: 'Oakwood', id: '940GZZLUOAK' },
    { name: 'Old Street', id: '940GZZLUODS' },
    { name: 'Osterley', id: '940GZZLUOSY' },
    { name: 'Oval', id: '940GZZLUOVL' },
    { name: 'Oxford Circus', id: '940GZZLUOXC' },
    { name: 'Paddington', id: '940GZZLUPAH' },
    { name: 'Park Royal', id: '940GZZLUPKR' },
    { name: 'Parsons Green', id: '940GZZLUPSG' },
    { name: 'Perivale', id: '940GZZLUPVL' },
    { name: 'Piccadilly Circus', id: '940GZZLUPCC' },
    { name: 'Pimlico', id: '940GZZLUPCO' },
    { name: 'Pinner', id: '940GZZLUPNR' },
    { name: 'Plaistow', id: '940GZZLUPLW' },
    { name: 'Preston Road', id: '940GZZLUPRD' },
    { name: 'Putney Bridge', id: '940GZZLUPYB' },
    { name: 'Queens Park', id: '940GZZLUQPS' },
    { name: 'Queensbury', id: '940GZZLUQBY' },
    { name: 'Queensway', id: '940GZZLUQWY' },
    { name: 'Ravenscourt Park', id: '940GZZLURVP' },
    { name: 'Rayners Lane', id: '940GZZLURYL' },
    { name: 'Reading', id: '910GRDNGSTN' },
    { name: 'Redbridge', id: '940GZZLURBG' },
    { name: 'Regents Park', id: '940GZZLURGP' },
    { name: 'Richmond', id: '940GZZLURMD' },
    { name: 'Rickmansworth', id: '940GZZLURKW' },
    { name: 'Roding Valley', id: '940GZZLURVY' },
    { name: 'Romford', id: '910GROMFORD' },
    { name: 'Royal Oak', id: '940GZZLURYO' },
    { name: 'Ruislip', id: '940GZZLURSP' },
    { name: 'Ruislip Gardens', id: '940GZZLURSG' },
    { name: 'Ruislip Manor', id: '940GZZLURSM' },
    { name: 'Russell Square', id: '940GZZLURSQ' },
    { name: 'Seven Kings', id: '910GSVNKNGS' },
    { name: 'Seven Sisters', id: '940GZZLUSVS' },
    { name: 'Shenfield', id: '910GSHENFLD' },
    { name: 'Shepherds Bush', id: '940GZZLUSBC' },
    { name: 'Shepherds Bush Market', id: '940GZZLUSBM' },
    { name: 'Sloane Square', id: '940GZZLUSSQ' },
    { name: 'Slough', id: '910GSLOUGH' },
    { name: 'Snaresbrook', id: '940GZZLUSNB' },
    { name: 'South Ealing', id: '940GZZLUSEA' },
    { name: 'South Harrow', id: '940GZZLUSHH' },
    { name: 'South Kensington', id: '940GZZLUSKS' },
    { name: 'South Kenton', id: '940GZZLUSKT' },
    { name: 'South Ruislip', id: '940GZZLUSRP' },
    { name: 'South Wimbledon', id: '940GZZLUSWN' },
    { name: 'South Woodford', id: '940GZZLUSWF' },
    { name: 'Southall', id: '910GSTHALL' },
    { name: 'Southfields', id: '940GZZLUSFS' },
    { name: 'Southgate', id: '940GZZLUSGT' },
    { name: 'Southwark', id: '940GZZLUSWK' },
    { name: 'St Johns Wood', id: '940GZZLUSJW' },
    { name: 'St. Jamess Park', id: '940GZZLUSJP' },
    { name: 'St. Pauls', id: '940GZZLUSPU' },
    { name: 'Stamford Brook', id: '940GZZLUSFB' },
    { name: 'Stanmore', id: '940GZZLUSTM' },
    { name: 'Stepney Green', id: '940GZZLUSGN' },
    { name: 'Stockwell', id: '940GZZLUSKW' },
    { name: 'Stonebridge Park', id: '940GZZLUSGP' },
    { name: 'Stratford', id: '940GZZDLSTD' },
    { name: 'Sudbury Hill', id: '940GZZLUSUH' },
    { name: 'Sudbury Town', id: '940GZZLUSUT' },
    { name: 'Swiss Cottage', id: '940GZZLUSWC' },
    { name: 'Taplow', id: '910GTAPLOW' },
    { name: 'Temple', id: '940GZZLUTMP' },
    { name: 'Theydon Bois', id: '940GZZLUTHB' },
    { name: 'Tooting Bec', id: '940GZZLUTBC' },
    { name: 'Tooting Broadway', id: '940GZZLUTBY' },
    { name: 'Tottenham Court Road', id: '940GZZLUTCR' },
    { name: 'Tottenham Hale', id: '940GZZLUTMH' },
    { name: 'Totteridge & Whetstone', id: '940GZZLUTAW' },
    { name: 'Tower Hill', id: '940GZZLUTWH' },
    { name: 'Tufnell Park', id: '940GZZLUTFP' },
    { name: 'Turnham Green', id: '940GZZLUTNG' },
    { name: 'Turnpike Lane', id: '940GZZLUTPN' },
    { name: 'Twyford', id: '910GTWYFORD' },
    { name: 'Upminster', id: '940GZZLUUPM' },
    { name: 'Upminster Bridge', id: '940GZZLUUPB' },
    { name: 'Upney', id: '940GZZLUUPY' },
    { name: 'Upton Park', id: '940GZZLUUPK' },
    { name: 'Uxbridge', id: '940GZZLUUXB' },
    { name: 'Vauxhall', id: '940GZZLUVXL' },
    { name: 'Victoria', id: '940GZZLUVIC' },
    { name: 'Walthamstow Central', id: '940GZZLUWWL' },
    { name: 'Wanstead', id: '940GZZLUWSD' },
    { name: 'Warren Street', id: '940GZZLUWRR' },
    { name: 'Warwick Avenue', id: '940GZZLUWKA' },
    { name: 'Waterloo', id: '940GZZLUWLO' },
    { name: 'Watford', id: '940GZZLUWAF' },
    { name: 'Wembley Central', id: '940GZZLUWYC' },
    { name: 'Wembley Park', id: '940GZZLUWYP' },
    { name: 'West Acton', id: '940GZZLUWTA' },
    { name: 'West Brompton', id: '940GZZLUWBN' },
    { name: 'West Drayton', id: '910GWDRYTON' },
    { name: 'West Ealing', id: '910GWEALING' },
    { name: 'West Finchley', id: '940GZZLUWFN' },
    { name: 'West Ham', id: '940GZZDLWHM' },
    { name: 'West Hampstead', id: '940GZZLUWHP' },
    { name: 'West Harrow', id: '940GZZLUWHW' },
    { name: 'West Kensington', id: '940GZZLUWKN' },
    { name: 'West Ruislip', id: '940GZZLUWRP' },
    { name: 'Westbourne Park', id: '940GZZLUWSP' },
    { name: 'Westminster', id: '940GZZLUWSM' },
    { name: 'White City', id: '940GZZLUWCY' },
    { name: 'Whitechapel', id: '940GZZLUWPL' },
    { name: 'Willesden Green', id: '940GZZLUWIG' },
    { name: 'Willesden Junction', id: '940GZZLUWJN' },
    { name: 'Wimbledon', id: '940GZZCRWMB' },
    { name: 'Wimbledon Park', id: '940GZZLUWIP' },
    { name: 'Wood Green', id: '940GZZLUWOG' },
    { name: 'Wood Lane', id: '940GZZLUWLA' },
    { name: 'Woodford', id: '940GZZLUWOF' },
    { name: 'Woodside Park', id: '940GZZLUWOP' },
    { name: 'Woolwich', id: '910GWOLWXR' },
  ];

  const LINE_COLORS = {
    "bakerloo": "#B36305",
    "central": "#E32017",
    "circle": "#FFD300",
    "district": "#00782A",
    "hammersmith & city": "#F3A9BB",
    "jubilee": "#A0A5A9",
    "metropolitan": "#9B0056",
    "northern": "#000000",
    "piccadilly": "#003688",
    "victoria": "#0098D4",
    "waterloo & city": "#95CDBA",
    "dlr": "#00A4A7",
    "elizabeth line": "#6950A1",
  };

  function stationNames() {
    return STATIONS.map(s => s.name);
  }

  function stationId(name) {
    const s = STATIONS.find(s => s.name === name);
    return s ? s.id : null;
  }

  function lineColor(lineName) {
    return LINE_COLORS[String(lineName || "").toLowerCase()] || "#8089a6";
  }

  // TfL StopPoint/{id}/Arrivals response -> filtered/sorted arrival list.
  function parseArrivals(json, opts) {
    const list = Array.isArray(json) ? json : [];
    const direction = (opts && opts.direction || "All").toLowerCase();
    const lineFilter = (opts && opts.lineFilter || "All");
    const lineFilterLower = lineFilter === "All" ? "" : lineFilter.trim().toLowerCase();
    const walkBufferSec = Math.max(0, (opts && opts.walkBufferMin) || 0) * 60;

    const out = [];
    for (const p of list) {
      if (!p || typeof p.timeToStation !== "number") continue;
      if (p.timeToStation < walkBufferSec) continue;
      if (lineFilterLower && !String(p.lineName || "").toLowerCase().includes(lineFilterLower)) continue;
      // Direction is frequently absent on TfL Underground predictions — only
      // filter when TfL actually reports one, don't hide arrivals of unknown direction.
      if (direction !== "all" && p.direction && String(p.direction).toLowerCase() !== direction) continue;

      out.push({
        line: p.lineName || "",
        destination: p.destinationName || p.towards || "",
        platform: p.platformName || "",
        seconds: p.timeToStation,
      });
    }
    out.sort((a, b) => a.seconds - b.seconds);
    return out.slice(0, 10);
  }

  // TfL Line/Mode/.../Status response -> [{name, status, good}].
  function parseLineStatuses(json) {
    const lines = Array.isArray(json) ? json : [];
    const out = [];
    for (const l of lines) {
      if (!l || !l.name) continue;
      const statuses = Array.isArray(l.lineStatuses) ? l.lineStatuses : [];
      const desc = statuses[0] && statuses[0].statusSeverityDescription || "Unknown";
      out.push({ name: l.name, status: desc, good: desc === "Good Service" });
    }
    return out;
  }

  // 90 -> "Due", 125 -> "2 min"
  function fmtCountdown(seconds) {
    if (typeof seconds !== "number" || !Number.isFinite(seconds)) return "—";
    if (seconds <= 30) return "Due";
    return Math.round(seconds / 60) + " min";
  }

  globalThis.Tube = {
    stationNames, stationId, lineColor, parseArrivals, parseLineStatuses, fmtCountdown,
  };
})();
